
name: Tag and Release

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user identity
        run: |
          git config --global user.email "ahrar@deriv.com"
          git config --global user.name "Ahrar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag and Release
        run: |
          latest_commit=$(git rev-parse HEAD)
          tag_name="auto-merge-$(date +'%Y%m%d%H%M%S')"  # Set the desired tag name
          git tag -a "$tag_name" $latest_commit -m "Automated tag for release"
          git push origin "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

