name: Bump release version
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        WITH_V: true

    - name: Tagged release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ steps.tag.outputs.tag }}: [title-edit-me] by:${{ github.actor }}"
          automatic_release_tag: ${{ steps.tag.outputs.new_tag }}
          files: |
            LICENSE.txt
